#!/bin/bash

alias ll='ls -alF'

alias push='git push origin --follow-tags'

function tag()
{
  if [[ $(git status -s) ]];
    then
      echo "Git repo has uncommitted changes."
      git status -s;
    else
      git tag -a "v${1}" -m "v${1}";
  fi
}

function dev ()
{
  if [ -f composer.json ]
    then
      symfony server:start --no-tls
  fi
}

function build ()
{
  if [ -f composer.json ]
    then
      vendor/bin/php-cs-fixer fix
      bin/phpunit
  fi
}
